from .password_reset import APIChangePasswordView
from .cancel_appointment import AppointmentCancelAPIView
from .doctor import DoctorPatientsListAPIView
from .patient import PatientDoctorsListAPIView
from .auth_for_doctor import DoctorRegisterAPIView
from .auth_for_patient import PatientRegisterAPIView
from .appointment import AppointmentsListAPIView